name = "qianshe-portfolio"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# 静态资源配置
[site]
bucket = "./dist"

# 路由配置
[env.production.routes]
pattern = "qianshe.top/*"
zone_name = "qianshe.top"

# 环境变量
[vars]
ENVIRONMENT = "development"
SITE_URL = "http://localhost:8787"
API_BASE_URL = "http://localhost:8787"
JWT_SECRET = "dev-jwt-secret-change-in-production"

# 本地开发环境
[env.development]
vars = { ENVIRONMENT = "development" }
kv_namespaces = [
  { binding = "CACHE_KV", id = "qianshe-cache-dev", preview_id = "qianshe-cache-dev-preview" }
]

[[env.development.d1_databases]]
binding = "SHARED_DB"
database_name = "qianshe-db-dev"
database_id = "your-local-d1-id"

# 生产环境
[env.production]
vars = { ENVIRONMENT = "production", SITE_URL = "https://qianshe.top", API_BASE_URL = "https://qianshe.top", JWT_SECRET = "your-production-jwt-secret" }

kv_namespaces = [
  { binding = "CACHE_KV", id = "qianshe-cache-prod" }
]

[[env.production.d1_databases]]
binding = "SHARED_DB"
database_name = "qianshe-db"
database_id = "your-production-d1-id"

# R2 存储绑定（用于文件上传）
[[r2_buckets]]
binding = "UPLOADS_BUCKET"
bucket_name = "qianshe-uploads"

# 性能和限制配置
[limits]
cpu_ms = 50000
memory = "128MB"

# 构建配置
[build]
command = "cd ../portfolio-frontend && npm run build"
