name = "qianshe-portfolio"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# 静态资源配置
[site]
bucket = "./dist"

# 路由配置
[env.production.routes]
pattern = "qianshe.dpdns.org/*"
zone_name = "qianshe.dpdns.org"

# 环境变量
[vars]
ENVIRONMENT = "development"
SITE_URL = "http://localhost:8787"
API_BASE_URL = "http://localhost:8787"
JWT_SECRET = "dev-jwt-secret-change-in-production"

# 本地开发环境
[env.development]
vars = { ENVIRONMENT = "development" }
kv_namespaces = [
  { binding = "CACHE_KV", id = "your-base-kv-id-here", preview_id = "your-base-kv-preview-id" }  # BASE_KV
]

[[env.development.d1_databases]]
binding = "SHARED_DB"
database_name = "my_d1"
database_id = "your-d1-id-here"  # 请替换为你的 D1 database_id

# 生产环境
[env.production]
vars = { ENVIRONMENT = "production", SITE_URL = "https://qianshe.dpdns.org", API_BASE_URL = "https://qianshe.dpdns.org", JWT_SECRET = "your-production-jwt-secret" }

kv_namespaces = [
  { binding = "CACHE_KV", id = "your-base-kv-id-here" }  # BASE_KV
]

[[env.production.d1_databases]]
binding = "SHARED_DB"
database_name = "my_d1"
database_id = "your-d1-id-here"  # 同一个 D1 ID

# R2 存储绑定（用于文件上传）
[[r2_buckets]]
binding = "UPLOADS_BUCKET"
bucket_name = "qianshe-uploads"

# 性能和限制配置
[limits]
cpu_ms = 50000
memory = "128MB"

# 构建配置
[build]
command = "cd ../portfolio-frontend && npm run build"
