# Cloudflare Workers 配置（生产环境模板）
# 本地开发请使用 wrangler.local.toml
name = "qianshe-portfolio"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# 静态资源配置（新的 assets 配置）
[observability]
enabled = true

[assets]
directory = "./dist"
binding = "ASSETS"

# 生产环境路由配置
[env.production.routes]
pattern = "qianshe.dpdns.org/*"
zone_name = "qianshe.dpdns.org"

# 生产环境变量（需在 Cloudflare Dashboard 或部署时配置）
[env.production.vars]
ENVIRONMENT = "production"
SITE_URL = "https://qianshe.dpdns.org"
API_BASE_URL = "https://qianshe.dpdns.org"
# JWT_SECRET - 在 Cloudflare Dashboard 中配置

# 生产环境 KV 存储绑定
[[env.production.kv_namespaces]]
binding = "CACHE"
id = "your-cache-kv-id-here"

# 生产环境 D1 数据库绑定
[[env.production.d1_databases]]
binding = "SHARED_DB"
database_name = "qianshe-db"
database_id = "your-d1-database-id-here"

# 生产环境 R2 存储绑定
[[env.production.r2_buckets]]
binding = "UPLOAD_BUCKET"
bucket_name = "qianshe-uploads"

# 性能和限制配置
[limits]
cpu_ms = 50000
memory = "128MB"

# 构建配置
[build]
command = "cd ../portfolio-frontend && npm run build"
